/*
 * UART_CONFIG.h
 *
 *  Created on: Aug 22, 2021
 *      Author: User
 */

#ifndef MCAL_USART_USART_CONFIG_H_
#define MCAL_USART_USART_CONFIG_H_

#define DISABLE								0
#define	ENABLE								1

#define USART_TRANSMIT_MODE 				DISABLE
#define USART_RECEIVE_MODE					ENABLE

#define USART_BIT_5_MODE					0
#define USART_BIT_6_MODE					1
#define USART_BIT_7_MODE					2
#define USART_BIT_8_MODE					3
#define USART_BIT_9_MODE					4

#define UART_BIT_SETTING 					USART_BIT_8_MODE

#define USART_ASYNCHRONOUS_OPERATION		0
#define USART_SYNCHRONOUS_OPERATION			1

#define USART_OPERATION_MODE				USART_ASYNCHRONOUS_OPERATION

#define USART_ASYNCHRONOUS_NORMAL_SPEED		0
#define USART_ASYNCHRONOUS_DOUBLE_SPEED		1

#define USART_ASYNCHRONOUS_SPEED			USART_ASYNCHRONOUS_NORMAL_SPEED

#define USART_PARITY_DISABELED 				0
#define USART_PARITY_REVERSED  				1
#define USART_EVEN_PARITY					2
#define USART_ODD_PARITY					3

#define USART_PARITY_MODE					USART_PARITY_DISABELED

#define UART_BIT_1_STOP_MODE				0
#define UART_BIT_2_STOP_MODE     			1

#define USART_BIT_MODE						UART_BIT_2_STOP_MODE

#define USART_RISING_EDGE					0
#define USART_FALLING_EDGE					1

#define USART_CLOCK_PARITY					USART_RISING_EDGE

#define FREQ_CPU							16000000UL
#define USART_BAUDRATE						9600UL
#define USART_BAUD_PRESCALE_NORMAL_SPEED	(((FREQ_CPU / (USART_BAUDRATE*16UL)))-1)
#define USART_BAUD_PRESCALE_DOUBLE_SPEED	(((FREQ_CPU / (USART_BAUDRATE*8UL)))-1)

#define USART_BAUD_NORMAL_SPEED_EQUATION	0
#define USART_BAUD_DOUBLE_SPEED_EQUATION	1


#define USART_BAUD_PRESCALE_EQUATION		USART_BAUD_NORMAL_SPEED_EQUATION

#define USART_TX_INTERRUNPT_MODE			DISABLE
#define USART_RX_INTERRUNPT_MODE			DISABLE



#endif /* MCAL_USART_USART_CONFIG_H_ */
